[package]
name = "cutix-project"
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
serde = { workspace = true }
serde_json = { version = "1.0", features = ["preserve_order"] }
uuid = { workspace = true }
dirs = "6.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
template = { version = "0.1.0", path = "../template" }
time = { version = "0.1.0", path = "../time" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mp4 = "0.14"
video = { version = "0.1.0", path = "../video" }

[dev-dependencies]
fixtures = { version = "0.1.0", path = "../fixtures" }
tempfile = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }

[lints]
workspace = true
