[package]
name = "speech"
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
thiserror = { workspace = true }
ureq = "2.10"
misaki-rs = { version = "0.3", default-features = false }
serde_json = { workspace = true }

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
ort = { version = "2.0.0-rc.10", features = ["download-binaries"] }

[target.'cfg(not(all(windows, target_arch = "x86_64")))'.dependencies]
ort = { version = "2.0.0-rc.10", default-features = false, features = ["load-dynamic", "ndarray"] }

[lints]
workspace = true
